-- ==============================================================================
-- 🏙️ NAMMA SAFE BLR — SMART CITY DIGITAL TWIN MIGRATION
-- ==============================================================================

-- 1. City Metrics
CREATE TABLE IF NOT EXISTS public.city_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    overall_safety_index FLOAT NOT NULL,
    traffic_index FLOAT NOT NULL,
    crowd_density_index FLOAT NOT NULL,
    weather_severity_index FLOAT NOT NULL,
    hazard_count INT NOT NULL DEFAULT 0,
    emergency_response_time INT NOT NULL DEFAULT 0, -- in minutes
    parking_occupancy FLOAT NOT NULL DEFAULT 0.0,
    transport_efficiency FLOAT NOT NULL DEFAULT 0.0,
    active_navigation_sessions INT NOT NULL DEFAULT 0,
    sos_requests INT NOT NULL DEFAULT 0
);

-- 2. City Predictions
CREATE TABLE IF NOT EXISTS public.city_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    time_horizon INT NOT NULL, -- 15, 30, 60 (minutes)
    predicted_traffic_index FLOAT NOT NULL,
    predicted_crime_risk FLOAT NOT NULL,
    predicted_weather_severity FLOAT NOT NULL,
    predicted_parking_occupancy FLOAT NOT NULL,
    predicted_crowd_density FLOAT NOT NULL,
    predicted_hazard_risk FLOAT NOT NULL,
    predicted_emergency_load FLOAT NOT NULL,
    predicted_transport_congestion FLOAT NOT NULL,
    confidence_score FLOAT NOT NULL -- 0 to 1
);

-- 3. City Alerts & Insights
CREATE TABLE IF NOT EXISTS public.city_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    category VARCHAR NOT NULL, -- traffic, weather, hazard, crime, crowd, parking, transport, emergency
    severity VARCHAR NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    message TEXT NOT NULL,
    location_lat FLOAT,
    location_lon FLOAT,
    is_active BOOLEAN DEFAULT TRUE
);

-- 4. Transport Status (Mock data for Dashboard)
CREATE TABLE IF NOT EXISTS public.transport_status (
    id VARCHAR PRIMARY KEY, -- e.g., 'bus-42'
    type VARCHAR NOT NULL, -- bus, metro
    route VARCHAR NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    occupancy_percent FLOAT NOT NULL,
    status VARCHAR NOT NULL, -- ON_TIME, DELAYED
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- 5. Parking Status (Mock data for Dashboard)
CREATE TABLE IF NOT EXISTS public.parking_status (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    capacity INT NOT NULL,
    occupied INT NOT NULL,
    occupancy_percent FLOAT NOT NULL,
    is_safe BOOLEAN DEFAULT TRUE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Enable Realtime
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'city_metrics') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.city_metrics;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'city_alerts') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.city_alerts;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'transport_status') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.transport_status;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'parking_status') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.parking_status;
  END IF;
END $$;

-- Policies (Allow read/write for demo purposes without strict auth here)
-- (assuming policies are set elsewhere or anon can read)
