-- ═══════════════════════════════════════════════════════════════════════════
-- SafeRoute AI — Google Auth Migration & Verification Script
-- ═══════════════════════════════════════════════════════════════════════════
-- Run this in Supabase SQL Editor AFTER enabling Google provider.
-- Safe to run multiple times.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── STEP 1: Ensure profiles table exists with all required columns ──────────
create table if not exists public.profiles (
  id            bigint generated by default as identity primary key,
  user_id       uuid   not null references auth.users(id) on delete cascade,
  full_name     text   not null default 'Anonymous',
  email         text,
  phone_number  text,
  avatar_url    text,
  provider      text   not null default 'email',  -- email | google | apple | phone
  country       text   default 'India',
  city          text   default 'Bengaluru',
  role          text   not null default 'viewer',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_login    timestamptz not null default now(),
  constraint profiles_user_id_unique unique (user_id)
);

-- ─── STEP 2: Add any missing columns (idempotent ALTER TABLE) ────────────────
do $$
begin
  -- avatar_url (may be missing in older schema)
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'avatar_url'
  ) then
    alter table public.profiles add column avatar_url text;
    raise notice 'Added avatar_url column to profiles';
  end if;

  -- provider
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'provider'
  ) then
    alter table public.profiles add column provider text not null default 'email';
    raise notice 'Added provider column to profiles';
  end if;

  -- last_login
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'last_login'
  ) then
    alter table public.profiles add column last_login timestamptz not null default now();
    raise notice 'Added last_login column to profiles';
  end if;

  -- updated_at
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'updated_at'
  ) then
    alter table public.profiles add column updated_at timestamptz not null default now();
    raise notice 'Added updated_at column to profiles';
  end if;
end;
$$;

-- ─── STEP 3: Enable Row Level Security ───────────────────────────────────────
alter table public.profiles enable row level security;

-- ─── STEP 4: RLS Policies ────────────────────────────────────────────────────
-- Drop and recreate to ensure they are current.
drop policy if exists "profiles_select_own"  on public.profiles;
drop policy if exists "profiles_insert_own"  on public.profiles;
drop policy if exists "profiles_update_own"  on public.profiles;
drop policy if exists "profiles_delete_own"  on public.profiles;

-- Users can only read their own profile
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = user_id);

-- Users can only insert their own profile row
create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = user_id);

-- Users can only update their own profile
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = user_id);

-- ─── STEP 5: Auto-create profile trigger on new user sign-up ─────────────────
-- This fires when any auth method is used (Google, Email, Apple, Phone).
-- The trigger runs as SECURITY DEFINER so it can bypass RLS to create the row.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
declare
  _provider  text := coalesce(new.raw_app_meta_data->>'provider', 'email');
  _full_name text := coalesce(
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'display_name',
    split_part(coalesce(new.email, ''), '@', 1),
    'User'
  );
  _avatar text := coalesce(
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'picture',
    null
  );
begin
  insert into public.profiles (
    user_id, full_name, email, phone_number, avatar_url, provider, last_login
  ) values (
    new.id,
    _full_name,
    new.email,
    new.phone,
    _avatar,
    _provider,
    now()
  )
  on conflict (user_id) do update set
    full_name  = coalesce(excluded.full_name,  profiles.full_name),
    avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
    email      = coalesce(excluded.email,      profiles.email),
    provider   = excluded.provider,
    last_login = now(),
    updated_at = now();
  return new;
end;
$$;

-- Drop and recreate the trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─── STEP 6: Update last_login on every sign-in ──────────────────────────────
create or replace function public.handle_user_login()
returns trigger language plpgsql security definer as $$
begin
  if new.last_sign_in_at is distinct from old.last_sign_in_at then
    update public.profiles
      set last_login = now(), updated_at = now()
      where user_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_login on auth.users;
create trigger on_auth_user_login
  after update on auth.users
  for each row execute function public.handle_user_login();

-- ─── STEP 7: Grant access to authenticated users ─────────────────────────────
grant usage  on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant usage, select on sequence public.profiles_id_seq to authenticated;

-- ─── STEP 8: Verification queries — run these to confirm everything works ─────

-- 8a. Confirm the profiles table exists and has the right columns
select column_name, data_type, is_nullable, column_default
from   information_schema.columns
where  table_schema = 'public' and table_name = 'profiles'
order  by ordinal_position;

-- 8b. Confirm RLS is enabled
select tablename, rowsecurity
from   pg_tables
where  schemaname = 'public' and tablename = 'profiles';

-- 8c. Confirm triggers exist on auth.users
select trigger_name, event_manipulation, action_timing
from   information_schema.triggers
where  event_object_schema = 'auth' and event_object_table = 'users';

-- 8d. After signing in with Google, run this to verify the profile was created:
--     (Replace the UUID with the user_id from auth.users after sign-in)
-- select * from auth.users order by created_at desc limit 5;
-- select * from profiles   order by created_at desc limit 5;
