-- ═══════════════════════════════════════════════════════════════════════════
-- SafeRoute AI — Road Hazards Migration
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. Create road_hazards table
create table if not exists public.road_hazards (
  id            bigint generated by default as identity primary key,
  user_id       uuid   references auth.users(id) on delete set null,
  hazard_type   text   not null,
  title         text   not null,
  description   text   not null default '',
  latitude      double precision not null,
  longitude     double precision not null,
  severity      integer not null default 5 check (severity between 1 and 10),
  status        text   not null default 'active',
  verified      boolean not null default false,
  image_url     text,
  source        text   not null default 'community',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- 2. Indexes
create index if not exists idx_road_hazards_latlon on public.road_hazards(latitude, longitude);
create index if not exists idx_road_hazards_user_id on public.road_hazards(user_id);

-- 3. Trigger for updated_at
drop trigger if exists set_updated_at on public.road_hazards;
create trigger set_updated_at
  before update on public.road_hazards
  for each row execute function public.handle_updated_at();

-- 4. Row Level Security
alter table public.road_hazards enable row level security;

drop policy if exists "road_hazards_select_all" on public.road_hazards;
drop policy if exists "road_hazards_insert_auth" on public.road_hazards;
drop policy if exists "road_hazards_update_own" on public.road_hazards;
drop policy if exists "road_hazards_delete_own" on public.road_hazards;

create policy "road_hazards_select_all" on public.road_hazards
  for select using (true);

create policy "road_hazards_insert_auth" on public.road_hazards
  for insert with check (auth.uid() = user_id or user_id is null);

create policy "road_hazards_update_own" on public.road_hazards
  for update using (auth.uid() = user_id);

create policy "road_hazards_delete_own" on public.road_hazards
  for delete using (auth.uid() = user_id);

-- 5. Storage Bucket for Hazard Images
insert into storage.buckets (id, name, public)
  values ('hazard-images', 'hazard-images', true)
  on conflict (id) do nothing;

drop policy if exists "hazard_images_upload" on storage.objects;
drop policy if exists "hazard_images_select" on storage.objects;

create policy "hazard_images_upload" on storage.objects
  for insert with check (bucket_id = 'hazard-images');

create policy "hazard_images_select" on storage.objects
  for select using (bucket_id = 'hazard-images');

-- ENABLE REALTIME
-- Check if publication exists, if not, it should be managed via Supabase dashboard or SQL:
-- alter publication supabase_realtime add table public.road_hazards;
