-- ═══════════════════════════════════════════════════════════════════════════
-- SafeRoute AI — Complete Supabase Schema (v2)
-- ═══════════════════════════════════════════════════════════════════════════
-- Apply in the Supabase SQL editor.
-- Safe to run multiple times (all statements use IF NOT EXISTS / OR REPLACE).
-- ═══════════════════════════════════════════════════════════════════════════

-- NOTE: pgcrypto and uuid-ossp are pre-installed in Supabase.
-- If running on a fresh custom PostgreSQL instance, enable them via:
--   Dashboard → Database → Extensions → enable pgcrypto and uuid-ossp
-- Do NOT run CREATE EXTENSION manually in the Supabase SQL Editor (permission denied).

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. PROFILES  (replaces old user_profiles; keeps backward compat via alias)
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.profiles (
  id            bigint generated by default as identity primary key,
  user_id       uuid   not null references auth.users(id) on delete cascade,
  full_name     text   not null default 'Anonymous',
  email         text,
  phone_number  text,
  avatar_url    text,
  provider      text   not null default 'email',  -- email | google | apple | phone | azure | github
  country       text   default 'India',
  city          text   default 'Bengaluru',
  role          text   not null default 'viewer',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_login    timestamptz not null default now(),
  constraint profiles_user_id_unique unique (user_id)
);

-- Backward-compat view so old code hitting user_profiles still works
-- Drop the old TABLE first (from schema v1) so we can create the view in its place
drop view if exists public.user_profiles cascade;
drop table if exists public.user_profiles cascade;
create or replace view public.user_profiles as
  select
    id,
    user_id::text,
    full_name  as display_name,
    email,
    phone_number as phone,
    role,
    created_at
  from public.profiles;

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION GUARD: Drop v1 tables that conflict with v2 schema
-- (v1 used TEXT for user_id; v2 uses UUID referencing auth.users)
-- CASCADE removes dependent RLS policies so we can recreate them cleanly.
-- Data in these tables is intentionally not preserved because the old
-- TEXT user_ids are not valid UUIDs and cannot be migrated automatically.
-- ═══════════════════════════════════════════════════════════════════════════
do $$
begin
  -- Only drop if the existing user_id column is TEXT (v1 schema)
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'route_history'
      and column_name  = 'user_id'
      and data_type    = 'text'
  ) then
    drop table if exists public.route_history cascade;
    raise notice 'Dropped v1 route_history (TEXT user_id)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'sos_requests'
      and column_name  = 'user_id'
      and data_type    = 'text'
  ) then
    drop table if exists public.sos_requests cascade;
    raise notice 'Dropped v1 sos_requests (TEXT user_id)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'incident_reports'
      and column_name  = 'user_id'
      and data_type    = 'text'
  ) then
    drop table if exists public.incident_reports cascade;
    raise notice 'Dropped v1 incident_reports (TEXT user_id)';
  end if;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. ROUTE HISTORY
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.route_history (
  id            bigint generated by default as identity primary key,
  user_id       uuid   not null references auth.users(id) on delete cascade,
  route_label   text   not null default 'Unknown',
  source        text   not null default 'Unknown',
  destination   text   not null default 'Unknown',
  distance_km   double precision default 0,
  duration_min  integer default 0,
  safety_score  integer default 0,
  risk_level    text   default 'MEDIUM',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. SAVED ROUTES
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.saved_routes (
  id            bigint generated by default as identity primary key,
  user_id       uuid   not null references auth.users(id) on delete cascade,
  route_name    text   not null default 'My Route',
  source        text   not null,
  destination   text   not null,
  src_lat       double precision,
  src_lon       double precision,
  dst_lat       double precision,
  dst_lon       double precision,
  route_type    text   default 'Safest',
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. INCIDENT REPORTS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.incident_reports (
  id            bigint generated by default as identity primary key,
  user_id       uuid   not null references auth.users(id) on delete cascade,
  latitude      double precision not null,
  longitude     double precision not null,
  description   text   not null default '',
  severity      integer not null default 5 check (severity between 1 and 10),
  status        text   not null default 'active',
  image_url     text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. TRAFFIC REPORTS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.traffic_reports (
  id                  bigint generated by default as identity primary key,
  user_id             uuid   references auth.users(id) on delete set null,
  road_name           text   not null,
  latitude            double precision not null,
  longitude           double precision not null,
  congestion_level    text   not null default 'MEDIUM',
  average_speed       double precision,
  vehicle_density     double precision,
  delay_minutes       double precision,
  traffic_percentage  double precision,
  status              text   default 'active',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. WEATHER REPORTS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.weather_reports (
  id            bigint generated by default as identity primary key,
  user_id       uuid   references auth.users(id) on delete set null,
  latitude      double precision not null,
  longitude     double precision not null,
  weather_type  text   not null,
  rainfall      double precision default 0,
  visibility    double precision default 10,
  flood_risk    double precision default 0,
  wind_speed    double precision default 10,
  humidity      double precision default 60,
  temperature   double precision default 25,
  source        text   default 'community',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. CROWD DENSITY REPORTS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.crowd_density_reports (
  id                bigint generated by default as identity primary key,
  user_id           uuid   references auth.users(id) on delete set null,
  latitude          double precision not null,
  longitude         double precision not null,
  crowd_level       text   not null default 'Moderate',
  crowd_score       double precision default 0.5,
  estimated_people  integer default 100,
  zone_type         text   default 'area',
  source            text   default 'community',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. SOS REQUESTS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.sos_requests (
  id          bigint generated by default as identity primary key,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  latitude    double precision,
  longitude   double precision,
  message     text   not null default 'SOS',
  status      text   not null default 'active',
  resolved_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 9. EMERGENCY REQUESTS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.emergency_requests (
  id                   bigint generated by default as identity primary key,
  user_id              uuid   references auth.users(id) on delete set null,
  vehicle_type         text   not null default 'Ambulance',
  source_latitude      double precision,
  source_longitude     double precision,
  destination_latitude double precision,
  destination_longitude double precision,
  priority_level       text   default 'high',
  status               text   default 'active',
  eta                  integer default 8,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 10. NOTIFICATIONS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  title       text   not null,
  body        text   not null,
  type        text   not null default 'info',  -- info | warning | danger | success
  is_read     boolean not null default false,
  data        jsonb  default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 11. FAVORITE LOCATIONS
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.favorite_locations (
  id          bigint generated by default as identity primary key,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  label       text   not null,
  latitude    double precision not null,
  longitude   double precision not null,
  icon        text   default '⭐',
  category    text   default 'custom',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 12. RECENT SEARCHES
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.recent_searches (
  id            bigint generated by default as identity primary key,
  user_id       uuid   not null references auth.users(id) on delete cascade,
  search_text   text   not null,
  latitude      double precision,
  longitude     double precision,
  source        text   default 'dataset',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint recent_searches_unique unique (user_id, search_text)
);

-- Legacy alias for frontend code that uses 'searched_locations'
-- Drop the old TABLE first (from schema v1) if it exists as a table
drop view if exists public.searched_locations cascade;
drop table if exists public.searched_locations cascade;
create or replace view public.searched_locations as
  select
    id,
    user_id::text,
    search_text,
    latitude,
    longitude,
    source,
    created_at
  from public.recent_searches;

-- ═══════════════════════════════════════════════════════════════════════════
-- INDEXES
-- ═══════════════════════════════════════════════════════════════════════════
create index if not exists idx_profiles_user_id         on public.profiles(user_id);
create index if not exists idx_route_history_user_id    on public.route_history(user_id);
create index if not exists idx_incident_reports_user_id on public.incident_reports(user_id);
create index if not exists idx_sos_requests_user_id     on public.sos_requests(user_id);
create index if not exists idx_emergency_user_id        on public.emergency_requests(user_id);
create index if not exists idx_notifications_user_id    on public.notifications(user_id);
create index if not exists idx_favorites_user_id        on public.favorite_locations(user_id);
create index if not exists idx_recent_searches_user_id  on public.recent_searches(user_id);
create index if not exists idx_traffic_reports_latlon   on public.traffic_reports(latitude, longitude);
create index if not exists idx_weather_reports_latlon   on public.weather_reports(latitude, longitude);
create index if not exists idx_crowd_reports_latlon     on public.crowd_density_reports(latitude, longitude);

-- ═══════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY — ENABLE
-- ═══════════════════════════════════════════════════════════════════════════
alter table public.profiles              enable row level security;
alter table public.route_history         enable row level security;
alter table public.saved_routes          enable row level security;
alter table public.incident_reports      enable row level security;
alter table public.traffic_reports       enable row level security;
alter table public.weather_reports       enable row level security;
alter table public.crowd_density_reports enable row level security;
alter table public.sos_requests          enable row level security;
alter table public.emergency_requests    enable row level security;
alter table public.notifications         enable row level security;
alter table public.favorite_locations    enable row level security;
alter table public.recent_searches       enable row level security;

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — PROFILES
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "profiles_select_own"  on public.profiles;
drop policy if exists "profiles_insert_own"  on public.profiles;
drop policy if exists "profiles_update_own"  on public.profiles;

create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = user_id);

create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = user_id);

create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — ROUTE HISTORY
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "route_history_select_own" on public.route_history;
drop policy if exists "route_history_insert_own" on public.route_history;

create policy "route_history_select_own" on public.route_history
  for select using (auth.uid() = user_id);

create policy "route_history_insert_own" on public.route_history
  for insert with check (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — SAVED ROUTES
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "saved_routes_select_own" on public.saved_routes;
drop policy if exists "saved_routes_insert_own" on public.saved_routes;
drop policy if exists "saved_routes_delete_own" on public.saved_routes;

create policy "saved_routes_select_own" on public.saved_routes
  for select using (auth.uid() = user_id);

create policy "saved_routes_insert_own" on public.saved_routes
  for insert with check (auth.uid() = user_id);

create policy "saved_routes_delete_own" on public.saved_routes
  for delete using (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — INCIDENT REPORTS (own + public read)
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "incidents_select_all"  on public.incident_reports;
drop policy if exists "incidents_insert_own"  on public.incident_reports;

create policy "incidents_select_all" on public.incident_reports
  for select using (true);

create policy "incidents_insert_own" on public.incident_reports
  for insert with check (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — TRAFFIC / WEATHER / CROWD (public read, own write)
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "traffic_select_all"  on public.traffic_reports;
drop policy if exists "traffic_insert_auth" on public.traffic_reports;
drop policy if exists "weather_select_all"  on public.weather_reports;
drop policy if exists "weather_insert_auth" on public.weather_reports;
drop policy if exists "crowd_select_all"    on public.crowd_density_reports;
drop policy if exists "crowd_insert_auth"   on public.crowd_density_reports;

create policy "traffic_select_all"  on public.traffic_reports       for select using (true);
create policy "traffic_insert_auth" on public.traffic_reports       for insert with check (auth.uid() is not null);
create policy "weather_select_all"  on public.weather_reports       for select using (true);
create policy "weather_insert_auth" on public.weather_reports       for insert with check (auth.uid() is not null);
create policy "crowd_select_all"    on public.crowd_density_reports for select using (true);
create policy "crowd_insert_auth"   on public.crowd_density_reports for insert with check (auth.uid() is not null);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — SOS REQUESTS
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "sos_select_own"  on public.sos_requests;
drop policy if exists "sos_insert_own"  on public.sos_requests;

create policy "sos_select_own" on public.sos_requests
  for select using (auth.uid() = user_id);

create policy "sos_insert_own" on public.sos_requests
  for insert with check (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — EMERGENCY REQUESTS (public insert, own select)
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "emergency_insert_any"  on public.emergency_requests;
drop policy if exists "emergency_select_own"  on public.emergency_requests;

create policy "emergency_insert_any" on public.emergency_requests
  for insert with check (true);

create policy "emergency_select_own" on public.emergency_requests
  for select using (auth.uid() is not null);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — NOTIFICATIONS
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "notifications_select_own"  on public.notifications;
drop policy if exists "notifications_update_own"  on public.notifications;

create policy "notifications_select_own" on public.notifications
  for select using (auth.uid() = user_id);

create policy "notifications_update_own" on public.notifications
  for update using (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- RLS POLICIES — FAVORITES + RECENT SEARCHES
-- ═══════════════════════════════════════════════════════════════════════════
drop policy if exists "favorites_own"       on public.favorite_locations;
drop policy if exists "recent_searches_own" on public.recent_searches;

create policy "favorites_own" on public.favorite_locations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "recent_searches_own" on public.recent_searches
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- STORAGE BUCKETS
-- ═══════════════════════════════════════════════════════════════════════════
-- Run these ONLY if the storage extension is enabled in your project:
insert into storage.buckets (id, name, public)
  values ('avatars',           'avatars',           true)
  on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
  values ('incident-images',   'incident-images',   false)
  on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
  values ('route-screenshots', 'route-screenshots', false)
  on conflict (id) do nothing;

-- Storage RLS: allow authenticated users to upload to their own folder
drop policy if exists "avatars_upload_own"   on storage.objects;
drop policy if exists "avatars_select_all"   on storage.objects;
drop policy if exists "incident_upload_own"  on storage.objects;
drop policy if exists "incident_select_own"  on storage.objects;

create policy "avatars_upload_own" on storage.objects
  for insert with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "avatars_select_all" on storage.objects
  for select using (bucket_id = 'avatars');

create policy "incident_upload_own" on storage.objects
  for insert with check (bucket_id = 'incident-images' and auth.uid() is not null);

create policy "incident_select_own" on storage.objects
  for select using (bucket_id = 'incident-images' and auth.uid() is not null);

-- ═══════════════════════════════════════════════════════════════════════════
-- TRIGGER: auto-update updated_at
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.handle_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'profiles','route_history','saved_routes','incident_reports',
    'traffic_reports','weather_reports','crowd_density_reports',
    'sos_requests','emergency_requests','notifications',
    'favorite_locations','recent_searches'
  ] loop
    execute format($f$
      drop trigger if exists set_updated_at on public.%I;
      create trigger set_updated_at
        before update on public.%I
        for each row execute function public.handle_updated_at();
    $f$, tbl, tbl);
  end loop;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- TRIGGER: auto-create profile on first sign-up (via auth.users insert)
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
declare
  _provider  text := coalesce(new.raw_app_meta_data->>'provider', 'email');
  _full_name text := coalesce(
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'display_name',
    split_part(coalesce(new.email, ''), '@', 1),
    'User'
  );
  _avatar    text := coalesce(
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'picture',
    null
  );
begin
  insert into public.profiles (user_id, full_name, email, phone_number, avatar_url, provider, last_login)
  values (
    new.id,
    _full_name,
    new.email,
    new.phone,
    _avatar,
    _provider,
    now()
  )
  on conflict (user_id) do update set
    full_name  = excluded.full_name,
    avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
    last_login = now(),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Also update last_login on sign-in (update of last_sign_in_at)
create or replace function public.handle_user_login()
returns trigger language plpgsql security definer as $$
begin  
  if new.last_sign_in_at is distinct from old.last_sign_in_at then
    update public.profiles
      set last_login = now(), updated_at = now()
      where user_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_login on auth.users;
create trigger on_auth_user_login
  after update on auth.users
  for each row execute function public.handle_user_login();


-- ==========================================
-- OFFLINE SYNC EXTENSION
-- ==========================================

-- 1. Offline Sync Status
create table if not exists public.offline_sync (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  device_id text not null,
  last_sync_time timestamptz not null default now(),
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. Sync Queue (Generic queue for varied payloads)
create table if not exists public.sync_queue (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  device_id text not null,
  operation_type text not null,
  payload jsonb not null default '{}',
  retry_count integer not null default 0,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3. Offline Navigation (Cached/Saved Routes)
create table if not exists public.offline_navigation (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  route_name text not null,
  route_data jsonb not null,
  city_key text,
  is_synced boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4. Offline Incidents
create table if not exists public.offline_incidents (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  client_id text not null,
  latitude double precision not null,
  longitude double precision not null,
  description text,
  severity integer,
  sync_status text not null default 'pending',
  reported_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5. Offline SOS
create table if not exists public.offline_sos (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  client_id text not null,
  latitude double precision,
  longitude double precision,
  message text,
  sync_status text not null default 'pending',
  triggered_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 6. Offline Tracking (GPS Trails)
create table if not exists public.offline_tracking (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  session_id text not null,
  track_points jsonb not null,
  sync_status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 7. Sync History
create table if not exists public.sync_history (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  device_id text,
  sync_type text not null,
  records_processed integer default 0,
  status text not null,
  error_message text,
  created_at timestamptz not null default now()
);
